### ISSUE TITLE
求附上2006年某仓管系统的下载地址

### ISSUE THREAD

**Issue by TomLiu-GitHub** [lishewen/WMSCrack#1]
求附上2006年某仓管系统的下载地址

**Comment by lishewen** [comment]
虽然是2006年的项目，但目前仍在服役，只是做这个系统的厂家倒闭了，客户想移到新机器移不了，故做了这个东西。原系统暂不提供，也许某一天没人用了会放出来。

**Comment by TomLiu-GitHub** [comment]
哼,留图不留种... 
我在做wms系统,想借鉴下

**Comment by lishewen** [comment]
可以借鉴这个
https://github.com/lishewen/WMS

**Comment by TomLiu-GitHub** [comment]
好巧,我刚clone了这个
